### ISSUE TITLE
fix the Nimbus CL launcher by passing a valid `--network`

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/eth2-package#53]
We currently seem to be passing path to a file for the network, it doesn't work.

Here are the logs

```
INF 2022-11-10 19:40:48.177+00:00 Launching beacon node                      topics="beacnde" version=v22.9.1-a84545-stateofus bls_backend=BLST cmdParams="@[\"--non-interactive=true\", \"--log-level=INFO\", \"--network=/genesis-data/output\", \"--data-dir=/root/consensus-data\", \"--web3-url=http://168.213.144.7:8551\", \"--nat=extip:168.213.144.11\", \"--enr-auto-update=false\", \"--rest\", \"--rest-address=0.0.0.0\", \"--rest-port=4000\", \"--validators-dir=/root/validator-keys\", \"--secrets-dir=/root/validator-secrets\", \"--doppelganger-detection=false\", \"--subscribe-all-subnets=true\", \"--num-threads=4\", \"--jwt-secret=/genesis-data/output/jwtsecret\", \"--metrics\", \"--metrics-address=0.0.0.0\", \"--metrics-port=8008\", \"--bootstrap-node=enr:-Ly4QH8b3iJKukfEPD1XDZoCFpmU7GQR9XI6kJgIqzdBhDDOV0cpPiCIYIlMx5JVignciuApPHn2W7eo8cVvRVUjc0YBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpA5-P2IMAAAOP__________gmlkgnY0gmlwhKjVkAmJc2VjcDI1NmsxoQIVCMARYv9Q1j-6kq9L5MEiYe2qKvzDgWqekewj_e9keYhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA\"]" config="(configFile: None[InputFile], logLevel: \"INFO\", logStdout: auto, logFile: None[OutFile], eth2Network: Some(\"/genesis-data/output\"), dataDir: /root/consensus-data, validatorsDirFlag: Some(/root/validator-keys), secretsDirFlag: Some(/root/validator-secrets), walletsDirFlag: None[InputDir], eraDirFlag: None[InputDir], web3Urls: @[\"http://168.213.144.7:8551\"], web3ForcePolling: false, requireEngineAPI: None[bool], nonInteractive: true, netKeyFile: \"random\", netKeyInsecurePassword: false, agentString: \"nimbus\", subscribeAllSubnets: true, slashingDbKind: v2, numThreads: 4, jwtSecret: Some(\"/genesis-data/output/jwtsecret\"), cmd: noCommand, runAsServiceFlag: false, bootstrapNodes: @[\"enr:-Ly4QH8b3iJKukfEPD1XDZoCFpmU7GQR9XI6kJgIqzdBhDDOV0cpPiCIYIlMx5JVignciuApPHn2W7eo8cVvRVUjc0YBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpA5-P2IMAAAOP__________gmlkgnY0gmlwhKjVkAmJc2VjcDI1NmsxoQIVCMARYv9Q1j-6kq9L5MEiYe2qKvzDgWqekewj_e9keYhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA\"], bootstrapNodesFile: , listenAddress: 0.0.0.0, tcpPort: 9000, udpPort: 9000, maxPeers: 160, hardMaxPeers: None[int], nat: (hasExtIp: true, extIp: 168.213.144.11), enrAutoUpdate: false, weakSubjectivityCheckpoint: None[Checkpoint], syncLightClient: false, trustedBlockRoot: None[Eth2Digest], finalizedCheckpointState: None[InputFile], finalizedCheckpointBlock: None[InputFile], nodeName: \"\", graffiti: None[GraffitiBytes], strictVerification: false, stopAtEpoch: 0, stopAtSyncedEpoch: 0, metricsEnabled: true, metricsAddress: 0.0.0.0, metricsPort: 8008, statusBarEnabled: true, statusBarContents: \"peers: $connected_peers;finalized: $finalized_root:$finalized_epoch;head: $head_root:$head_epoch:$head_epoch_slot;time: $epoch:$epoch_slot ($slot);sync: $sync_status|ETH: $attached_validators_balance\", rpcEnabled: None[bool], rpcPort: None[Port], rpcAddress: None[ValidIpAddress], restEnabled: true, restPort: 4000, restAddress: 0.0.0.0, restAllowedOrigin: None[TaintedString], restCacheSize: 3, restCacheTtl: 60, restRequestTimeout: 0, restMaxRequestBodySize: 16384, restMaxRequestHeadersSize: 64, keymanagerEnabled: false, keymanagerPort: 5052, keymanagerAddress: 127.0.0.1, keymanagerAllowedOrigin: None[TaintedString], keymanagerTokenFile: None[InputFile], lightClientDataServe: true, lightClientDataImportMode: only-new, lightClientDataMaxPeriods: None[uint64], inProcessValidators: true, debugForkChoice: false, discv5Enabled: true, dumpEnabled: false, directPeers: @[], doppelgangerDetection: false, syncHorizon: 50, terminalTotalDifficultyOverride: None[TaintedString], validatorMonitorAuto: false, validatorMonitorPubkeys: @[], validatorMonitorTotals: false, safeSlotsToImportOptimistically: None[uint16], suggestedFeeRecipient: None[Address], payloadBuilderEnable: false, payloadBuilderUrl: \"\")"
NOT 2022-11-10 19:40:48.177+00:00 Starting metrics HTTP server               topics="beacnde" url=http://0.0.0.0:8008/metrics
INF 2022-11-10 19:40:48.181+00:00 Threadpool started                         topics="beacnde" numThreads=4
NOT 2022-11-10 19:40:48.237+00:00 New database from snapshot                 topics="beacnde" genesisBlockRoot=25781dd2 genesisStateRoot=d9e0ff1b tailBlockRoot=25781dd2 tailStateRoot=d9e0ff1b fork="(previous_version: 10000038, current_version: 30000038, epoch: 0)" validators=128 tailStateSlot=0 genesisStateSlot=0
INF 2022-11-10 19:40:48.238+00:00 Loading block DAG from database            topics="beacnde" path=/root/consensus-data/db
ERR 2022-11-10 19:40:48.644+00:00 State from database does not match network, check --network parameter genesis=25781dd2:0 tail=25781dd2:0 headRef=25781dd2:0 stateFork="(previous_version: 10000038, current_version: 30000038, epoch: 0)" configFork="(previous_version: 20000038, current_version: 30000038, epoch: 0)"
```

How to reproduce?

Use the following YML to start the module

```
participants:
- elType: geth
  elImage: ethereum/client-go:v1.10.25
  clType: lighthouse
  clImage: sigp/lighthouse:v3.1.2
- elType: geth
  elImage: ethereum/client-go:v1.10.25
  clType: nimbus
  clImage: parithoshj/nimbus:merge-a845450
network:
  networkId: '3151908'
  depositContractAddress: '0x4242424242424242424242424242424242424242'
  secondsPerSlot: 12
  slotsPerEpoch: 32
  altairForkEpoch: 0
  mergeForkEpoch: 0
  totalTerminalDifficulty: 0
  numValidatorKeysPerNode: 64
  preregisteredValidatorKeysMnemonic: giant issue aisle success illegal bike spike
    question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy
    very lucky have athlete
waitForMining: false
waitForFinalization: true
waitForVerifications: true
verificationsEpochLimit: 5
logLevel: info
```
